################################# Default configuration ###################
baseURL = "http://github.com/ian08005454/ASCDC_intern"
title = "中央研究院實習成果"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
canonifyurls = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"

############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


############################## navigation ###############################

# main menu
[[menu.main]]
name = "公司環境"
URL = "about"
weight = 1

[[menu.main]]
name = "成果展示&畫廊"
URL = "project"
weight = 2

[[menu.main]]
name = "Service"
URL = "service"
weight = 3

[[menu.main]]
name = "實習筆記"
weight = 4
hasChildren = true
  [[menu.main]]
  parent = "實習筆記"
  name = "筆記主頁"
  URL = "blog"
  weight = 1
  [[menu.main]]
  parent = "實習筆記"
  name = "李韋杰"
  URL = "author/李韋杰"
  weight = 2



  

# footer menu
[[menu.footer]]
name = "Home"
URL = "#"
weight = 1

[[menu.footer]]
name = "公司環境"
URL = "about"
weight = 2

[[menu.footer]]
name = "成果展示&畫廊"
URL = "project"
weight = 3

[[menu.footer]]
name = "Service"
URL = "service"
weight = 4

[[menu.footer]]
name = "實習筆記"
URL = "blog"
weight = 5

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Academia Sinica intern reporter"
author = "Wei-Jie, Li"
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = false
label = "Get A Quote"
link = "Home"

################################ English Language ########################
[Languages.en]
languageName = "TW"
languageCode = "zh-tw"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright ="Copyright &copy; 2020 [中央研究院數位文化中心](https://ascdc.sinica.edu.tw/) All Rights Reserved"

[outputFormats]
  [outputFormats.MyEnrichedFormat]
    baseName = "index"
    isPlainText = true
    isHTML = true
    