################################# Default configuration ###################
baseURL = "https://ian08005454.github.io/ASCDC_intern/"
title = "中央研究院實習成果"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
canonifyurls = true
#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"

############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


############################## navigation ###############################

# main menu
[[menu.main]]
name = "數位人文平台介紹"
URL = "about"
weight = 1

[[menu.main]]
name = "成果展示"
URL = "project"
weight = 2

[[menu.main]]
name = "實習筆記"
weight = 3
hasChildren = true
  [[menu.main]]
  parent = "實習筆記"
  name = "筆記主頁"
  URL = "blog"
  weight = 1
  [[menu.main]]
  parent = "實習筆記"
  name = "李韋杰"
  URL = "author/李韋杰"
  weight = 2
  [[menu.main]]
  parent = "實習筆記"
  name = "李彥瑾"
  URL = "author/李彥瑾"
  weight = 3


# footer menu
[[menu.footer]]
name = "Home"
URL = "#"
weight = 1

[[menu.footer]]
name = "數位人文平台介紹"
URL = "about"
weight = 2

[[menu.footer]]
name = "成果展示"
URL = "project"
weight = 3

[[menu.footer]]
name = "實習筆記"
URL = "blog"
weight = 4

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Academia Sinica intern reporter"
author = "Wei-Jie, Li"
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xhtml = true
    [markup.tableOfContents]
      endLevel = 3
      ordered = false
      startLevel = 2
 
# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = false
label = "Get A Quote"
link = "Home"

################################ English Language ########################
[Languages.en]
languageName = "TW"
languageCode = "zh-tw"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright ="Copyright &copy; 2020 1061619李韋杰、1061653李彥瑾 All Rights Reserved"

[outputFormats]
  [outputFormats.MyEnrichedFormat]
    baseName = "index"
    isPlainText = true
    isHTML = true


    